### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by dominik-zeglen** [kiskadigitalmedia/Enduro#5]
Can anyone explain how exactly routes work in Enduro?
Or, how exactly can I setup route to send response only after POST request?

I tried to add 

`app.post("/route", function(req, res) {});`

but it doesn't seem to work. Any ideas?

**Comment by dominik-zeglen** [comment]
Okay, nevermind. Reinstalling Enduro solved problem.

**Comment by Gottwik** [comment]
Hey Dominik,

Thanks for using enduro.js. Feel free to report any bugs or questions I am super happy to help you.

Martin
